services:
  patientservicedb:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=patientdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=patientroot'
    ports:
      - '5432'

  patientservice:
    image: patientservice
    ports:
      - '8080:8080'