version: '2.1'
services:
  patientdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "patientroot"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "patientdb"
    volumes:

    networks:
      backend:
        aliases:
          - "patientdb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image:
    healthcheck:
      test: exit 0
      interval: 15s
      timeout: 3s
      retries: 10
    ports:
      - "8089:8089"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
      server.port: "8888"
    networks:
      backend:
        aliases:
          - "configserver"
  patientservice:
    image:
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8888/"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge