version: '2.1'
services:
  patientdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "patientdb_dev"
    #volumes:

    networks:
      backend:
        aliases:
          - "patientdb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 12s
      timeout: 5s
      retries: 5
  configserver:
    image: ehealth/configserver
    healthcheck:
      test: exit 0
      interval: 15s
      timeout: 3s
      retries: 10
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
      server.port: "8888"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: ehealth/eurekaserver
    environment:
      - "SPRING_PROFILES_ACTIVE=standalone"
    ports:
      - "8070:8070"
    depends_on:
      patientdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "eurekaserver"
    healthcheck:
      test: exit 0
      interval: 10s
      timeout: 5s
      retries: 5
  gatewayserver:
    image: ehealth/gatewayserver
    container_name: gateway
    ports:
      - "8072:8072"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8072"
      CONFIGSERVER_URI: "http://configserver:8071"
      EUREKASERVER_URI: "http://eurekaserver:8070/eureka/"
      EUREKASERVER_PORT: "8070"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      patientdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "gateway"
  patientservice:
    image: ehealth/patientservice
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8888/"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
      PATIENTSERVICE_PORT: "8081"
    depends_on:
      patientdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend
  billingservice:
    image: ehealth/billingservice
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8888/"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
      BILLINGSERVICE_PORT: "8082"
    depends_on:
      patientdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge