version: '2.1'
volumes:
  keycloak:
services:
  patientdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "patientdb_prod"
    #volumes:

    networks:
      backend:
        aliases:
          - "patientdb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 12s
      timeout: 5s
      retries: 5
  configserver:
    image: ehealth/configserver
    healthcheck:
      test: exit 0
      interval: 25s
      timeout: 3s
      retries: 10
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
      server.port: "8888"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: ehealth/eurekaserver
    environment:
      - "SPRING_PROFILES_ACTIVE=standaloneprod"
    ports:
      - "8070:8070"
    depends_on:
      patientdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "eurekaserver"
    healthcheck:
      test: exit 0
      interval: 20s
      timeout: 5s
      retries: 5
  gatewayserver:
    image: ehealth/gatewayserver
    container_name: gateway
    ports:
      - "8072:8072"
    environment:
      PROFILE: "prod"
      SERVER_PORT: "8072"
      CONFIGSERVER_URI: "http://configserver:8071"
      EUREKASERVER_URI: "http://eurekaserver:8070/eureka/"
      EUREKASERVER_PORT: "8070"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      patientdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "gateway"
  patientservice:
    image: ehealth/patientservice
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://configserver:8888/"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
      PATIENTSERVICE_PORT: "8081"
    depends_on:
      patientdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend
  billingservice:
    image: ehealth/billingservice
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://configserver:8888/"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
      BILLINGSERVICE_PORT: "8082"
    depends_on:
      patientdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - backend
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      #KC_DB: postgres
      #KC_DB_ADDR: patientdb
      #KC_DB_DATABASE: keycloakdb
      #KC_DB_USERNAME: postgres
      #DB_SCHEMA: public
      #KC_DB_PASSWORD: postgres
      #KC_DB_URL: jdbc:postgresql://patientdb:5432/keycloakdb
      #KC_DB_URL_PORT: 5432
    volumes:
      - keycloak:/opt/keycloak/data/
    ports:
      - "9090:8080"
    networks:
      - backend

    command:
      - "start-dev"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2128
    ports:
      - 2181:2181
    networks:
      backend:
        aliases:
          - "zookeeper"
  kafkaserver:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper
    networks:
      backend:
        aliases:
          - "kafka"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    #environment:
#      - STORAGE_TYPE=elasticsearch
#      - "ES_HOSTS=elasticsearch:9300"
    ports:
      - "9411:9411"
    networks:
      backend:
        aliases:
          - "zipkin"


networks:
  backend:
    driver: bridge