apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eurekaserver
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eurekaserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prod.yml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/hospitalsystem-backend: "true"
        io.kompose.service: eurekaserver
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: standaloneprod
          image: ehealth/eurekaserver
          livenessProbe:
            exec:
              command:
                - exit 0
            failureThreshold: 5
            periodSeconds: 20
            timeoutSeconds: 5
          name: eurekaserver
          ports:
            - containerPort: 8070
              hostPort: 8070
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
